using module .\PaletteScriptAttributes.psm1

<#
.SYNOPSIS
    Markdown Cheat Sheet
.DESCRIPTION
    Show a polished Markdown reference with syntax examples, rendered output, and practical tips
#>
[ScriptGroup('Reference')]
[ScriptVersion('1.0.0')]
[ScriptIcon('📝')]
[ScriptTimeout(5000)]
[ScriptOutput('Markdown')]
param()

# Most lines are single-quoted so PowerShell does not treat backticks as escapes.
# Tables are self-referential: the syntax column shows what to type, and the
# preview column lets PaletteShell render the result.
$lines = @(
    '# Markdown Cheat Sheet'
    ''
    '_Copy-friendly syntax, rendered examples, and the little Markdown rules that are easy to forget._'
    ''
    '## Quick Syntax'
    ''
    '| Thing | Type this | Preview |'
    '| --- | --- | --- |'
    '| Heading | `# Heading` | # Heading |'
    '| Bold | `**important**` | **important** |'
    '| Italic | `*emphasis*` | *emphasis* |'
    '| Bold + italic | `***very important***` | ***very important*** |'
    '| Strikethrough | `~~removed~~` | ~~removed~~ |'
    '| Inline code | `` `Get-Process` `` | `Get-Process` |'
    '| Link | `[PaletteShell](https://github.com/paletteshell)` | [PaletteShell](https://github.com/paletteshell) |'
    '| Blockquote | `> note` | > note |'
    '| Horizontal rule | `---` | --- |'
    ''
    '## Headings'
    ''
    '```markdown'
    '# Page title'
    '## Section'
    '### Subsection'
    '#### Small heading'
    '```'
    ''
    'Use one `#` for the page title, then move downward one level at a time. A blank line before and after headings keeps rendering predictable.'
    ''
    '## Lists'
    ''
    '```markdown'
    '- First bullet'
    '- Second bullet'
    '  - Nested bullet'
    ''
    '1. First step'
    '2. Second step'
    '3. Third step'
    ''
    '- [ ] To do'
    '- [x] Done'
    '```'
    ''
    'Tip: keep ordered lists numbered `1. 2. 3.` when writing docs by hand. Some renderers renumber automatically, but explicit numbering is easier to scan in plain text.'
    ''
    '## Code'
    ''
    '| Use | Syntax |'
    '| --- | --- |'
    '| Inline command | `` `npm run build` `` |'
    '| Fenced block | ```` ```powershell<br>Get-Process<br>``` ```` |'
    '| Literal backtick | `` `` ` `` `` |'
    ''
    '```powershell'
    'Get-ChildItem -Path . -Filter *.ps1'
    '```'
    ''
    'Add a language name after the opening fence for highlighting: `powershell`, `json`, `csharp`, `typescript`, `bash`, `markdown`.'
    ''
    '## Tables'
    ''
    '```markdown'
    '| Name | Purpose |'
    '| --- | --- |'
    '| `Clipboard-PreviewMarkdown.ps1` | Render clipboard Markdown |'
    '| `View-SystemStatistics.ps1` | Show a system report |'
    '```'
    ''
    '| Alignment | Marker | Example |'
    '| --- | --- | --- |'
    '| Left | `:---` | text |'
    '| Center | `:---:` | text |'
    '| Right | `---:` | 123 |'
    ''
    'Escape literal pipes in table cells with a backslash: `A \| B`.'
    ''
    '## Links, Images, And References'
    ''
    '```markdown'
    '[Inline link](https://example.com)'
    ''
    '![Alt text](image.png)'
    ''
    '[Reference link][docs]'
    ''
    '[docs]: https://example.com/docs'
    '```'
    ''
    'Good alt text says what the image contributes, not just "image".'
    ''
    '## GitHub-Flavored Markdown'
    ''
    '| Feature | Syntax |'
    '| --- | --- |'
    '| Task list | `- [ ] Write docs` |'
    '| Mention | `@username` |'
    '| Issue or PR | `#123` |'
    '| Emoji shortcode | `:rocket:` |'
    '| Footnote | `Text with note[^1]` |'
    ''
    '```markdown'
    'Here is a footnote.[^1]'
    ''
    '[^1]: Footnote text goes here.'
    '```'
    ''
    '## Common Gotchas'
    ''
    '| Problem | Fix |'
    '| --- | --- |'
    '| Paragraphs run together | Add a blank line between blocks. |'
    '| A list does not nest | Indent nested items by two or four spaces. |'
    '| A pipe breaks a table | Escape it as `\|`. |'
    '| Code fence closes too early | Use more backticks around the outer fence. |'
    '| Markdown renders as plain text | Check for leading spaces or an unclosed code fence. |'
    ''
    '## Starter Template'
    ''
    '````markdown'
    '# Title'
    ''
    'Short intro paragraph.'
    ''
    '## Section'
    ''
    '- Key point'
    '- Another key point'
    ''
    '```powershell'
    'Write-Host "Example"'
    '```'
    '````'
)

Write-Host ($lines -join "`n")
