using module .\PaletteScriptAttributes.psm1

<#
.SYNOPSIS
    Regular Expressions Cheat Sheet
.DESCRIPTION
    Show a practical regular-expression reference with tokens, flags, recipes, and PowerShell examples
#>
[ScriptHost('pwsh')]
[ScriptGroup('Reference')]
[ScriptIcon('🔤')]
[ScriptTimeout(5000)]
[ScriptOutput('Markdown')]
param()

# Backslashes and pipes are escaped for Markdown table cells.
$lines = @(
    '# Regular Expressions Cheat Sheet'
    ''
    '_A quick reference for matching, extracting, replacing, and debugging text patterns._'
    ''
    '## Core Tokens'
    ''
    '| Pattern | Meaning | Example match |'
    '| --- | --- | --- |'
    '| `^` | Start of string, or line in multiline mode | start of `abc` |'
    '| `$` | End of string, or line in multiline mode | end of `abc` |'
    '| `.` | Any character except newline | `a`, `7`, `?` |'
    '| `\b` | Word boundary | before `word` |'
    '| `\B` | Not a word boundary | inside `word` |'
    '| `\d` / `\D` | Digit / non-digit | `5` / `A` |'
    '| `\w` / `\W` | Word char / non-word char | `A` / `-` |'
    '| `\s` / `\S` | Whitespace / non-whitespace | space / `x` |'
    '| `[abc]` | Any one listed character | `a` |'
    '| `[^abc]` | Any character except listed ones | `z` |'
    '| `[a-z]` | Character range | `q` |'
    '| `\.` `\*` `\\` | Literal `.`, `*`, or `\` | `.`, `*`, `\` |'
    ''
    '## Quantifiers'
    ''
    '| Pattern | Meaning | Example |'
    '| --- | --- | --- |'
    '| `*` | 0 or more | `\d*` matches empty text or `123` |'
    '| `+` | 1 or more | `\d+` matches `123` |'
    '| `?` | 0 or 1 | `https?` matches `http` or `https` |'
    '| `{n}` | Exactly n | `\d{4}` matches `2026` |'
    '| `{n,}` | n or more | `\w{3,}` matches `name` |'
    '| `{n,m}` | Between n and m | `\d{2,4}` matches `25` or `2026` |'
    '| `*?` `+?` `{n,m}?` | Lazy, as few as possible | `<.*?>` matches one tag at a time |'
    ''
    '## Groups And Alternation'
    ''
    '| Pattern | Meaning |'
    '| --- | --- |'
    '| `(abc)` | Capturing group |'
    '| `(?:abc)` | Non-capturing group |'
    '| `(?<name>abc)` | Named capturing group |'
    '| `a\|b` | Match `a` or `b` |'
    '| `\1` | Backreference to capture group 1 |'
    '| `\k<name>` | Backreference to named group |'
    ''
    '## Lookarounds'
    ''
    '| Pattern | Meaning | Example use |'
    '| --- | --- | --- |'
    '| `(?=...)` | Positive lookahead | `\d+(?=px)` matches number before `px` |'
    '| `(?!...)` | Negative lookahead | `foo(?!bar)` matches `foo` not followed by `bar` |'
    '| `(?<=...)` | Positive lookbehind | `(?<=\$)\d+` matches number after `$` |'
    '| `(?<!...)` | Negative lookbehind | `(?<!-)\d+` matches number not preceded by `-` |'
    ''
    '## Common Flags'
    ''
    '| Flag | Name | Effect |'
    '| --- | --- | --- |'
    '| `i` | Ignore case | `abc` matches `ABC` |'
    '| `m` | Multiline | `^` and `$` work per line |'
    '| `s` | Singleline / dotall | `.` also matches newline |'
    '| `x` | Ignore pattern whitespace | Allows readable, commented patterns |'
    ''
    'Inline flag syntax: `(?i)case-insensitive`, `(?m)^line`, `(?s)<body>.*</body>`.'
    ''
    '## Practical Recipes'
    ''
    '| Need | Pattern | Notes |'
    '| --- | --- | --- |'
    '| Email-ish text | `\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b` | Use ignore-case. Good for finding, not perfect validation. |'
    '| URL-ish text | `https?://[^\s<>"'']+` | Finds common HTTP/HTTPS URLs. |'
    '| IPv4 address | `\b(?:\d{1,3}\.){3}\d{1,3}\b` | Finds candidates; range validation is separate. |'
    '| ISO date | `\b\d{4}-\d{2}-\d{2}\b` | Example: `2026-07-02`. |'
    '| GUID | `\b[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}\b` | Common dashed GUID format. |'
    '| Quoted string | `"([^"\\]|\\.)*"` | Handles escaped characters. |'
    '| Markdown heading | `^(#{1,6})\s+(.+)$` | Use multiline mode. |'
    '| Blank lines | `(?m)^\s*$` | Match empty or whitespace-only lines. |'
    ''
    '## PowerShell Examples'
    ''
    '```powershell'
    '# Test whether text matches'
    '''release-2026'' -match ''\d{4}'''
    ''
    '# Read named captures'
    '''Name: Ada'' -match ''Name:\s+(?<name>\w+)'''
    '$Matches.name'
    ''
    '# Replace repeated whitespace'
    '''too    many     spaces'' -replace ''\s+'', '' '''
    ''
    '# Extract all matches'
    '[regex]::Matches(''a1 b22 c333'', ''\d+'') | ForEach-Object Value'
    '```'
    ''
    'PowerShell regex uses the .NET engine. In single-quoted PowerShell strings, backslashes stay literal, so patterns like `''\d+''` are usually easier to read.'
    ''
    '## Debugging Checklist'
    ''
    '| Symptom | Try |'
    '| --- | --- |'
    '| It matches too much | Make quantifiers lazy: `.*?`, or replace `.*` with a narrower class. |'
    '| It matches nothing | Check escaping and whether your anchors need multiline mode. |'
    '| Case differs | Add ignore-case with `(?i)` or the tool option. |'
    '| Newlines are involved | Use `(?m)` for line anchors or `(?s)` for dotall. |'
    '| Replacement is weird | Escape `$` carefully; replacement strings have their own rules. |'
    '| Pattern is unreadable | Break it into named groups or use `(?x)` extended mode. |'
)

Write-Host ($lines -join "`n")
